name: release

on:
  push:
    branches:
      - main

jobs:
    check:
    name: Run format & lint & build check
    uses: dashbrains/rubocop-config/.github/workflows/lint_format.yml@main

  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: GoogleCloudPlatform/release-please-action@v4
        id: release
        with:
          release-type: ruby
          package-name: dashbrains-rubocop-config
          bump-minor-pre-major: true
          version-file: "lib/dashbrains/rubocop/config/version.rb"
